one_wire:
  - platform: gpio
    setup_priority: 1000 #https://github.com/esphome/issues/issues/5983
    pin: ${onewire_pin}
    id: dallas_bus
    
button: # clic to find onewire devices address
  - platform: template
    name: "Test onewire bus"
    on_press:
        - lambda: |-
              id(dallas_bus).search();
              id(dallas_bus).dump_config();
    id: dallas_bus_test_bt
    web_server:
      sorting_group_id: sorting_group_actions
    
sensor:
  - platform: dallas_temp
    setup_priority: -100 #https://github.com/esphome/issues/issues/5983
    address: ${dallasaddress_input} #if only one device on bus, address is not needed
    name: Dallas Input temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-high"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    # fix since 2024.6 : https://github.com/esphome/issues/issues/5908
    # update_interval: never
    # filters:
      # - filter_out: nan
      # - filter_out: 85.0
    id: dallas_input_temp
    web_server:
      sorting_group_id: sorting_group_sensors
    

  - platform: dallas_temp
    setup_priority: -100 #https://github.com/esphome/issues/issues/5983
    address: ${dallasaddress_output}
    name: Dallas Output temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-low"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    # fix since 2024.6 : https://github.com/esphome/issues/issues/5908
    # update_interval: never
    # filters:
      # - filter_out: nan
      # - filter_out: 85.0
    id: dallas_output_temp
    web_server:
      sorting_group_id: sorting_group_sensors
    
# fix since 2024.6 : https://github.com/esphome/issues/issues/5908
# interval:
  # - interval: 60s
    # then:
      # - component.update: dallas_input_temp
      # - delay: 1s
      # - component.update: dallas_output_temp
      # - delay: 1s
    

  # - platform: dallas_temp
    # #address: 0x12345678
    # name: Dallas Spare temp
    # update_interval: 60s
    # accuracy_decimals: 2
    # id: dallas_3rd_temp