one_wire:
  - platform: gpio
    setup_priority: 1000 #https://github.com/esphome/issues/issues/5983
    pin: ${onewire_pin}
    id: ${id_prefix}dallas_bus
    
button: # clic to find onewire devices address (in logs)
  - platform: template
    name: "Test onewire bus"
    on_press:
        - lambda: |-
              id(${id_prefix}dallas_bus).search();
              id(${id_prefix}dallas_bus).dump_config();
    id: ${id_prefix}dallas_bus_test_bt
    # web_server:
      # sorting_group_id: sorting_group_actions
    
sensor:
  - platform: dallas_temp
    setup_priority: -100 #https://github.com/esphome/issues/issues/5983
    address: ${dallasaddress_input} #if only one device on bus, address is not needed
    name: Heating circuit Input temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-high"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    id: ${id_prefix}dallas_input_temp
    # web_server:
      # sorting_group_id: sorting_group_sensors
    

  - platform: dallas_temp
    setup_priority: -100 #https://github.com/esphome/issues/issues/5983
    address: ${dallasaddress_output}
    name: Heating circuit Output temp
    unit_of_measurement: "°C"
    icon: "mdi:thermometer-low"
    device_class: "temperature"
    state_class: "measurement"
    accuracy_decimals: 2
    update_interval: 60s
    id: ${id_prefix}dallas_output_temp
    # web_server:
      # sorting_group_id: sorting_group_sensors
    
