sensor:
  - platform: homeassistant
    name: "Living room temperature sensor from hassio"
    entity_id: sensor.woonkamer_tempratuur
    id: living_room_temperature_sensor

  - platform: homeassistant
    name: "Hal temperature sensor from hassio"
    entity_id: sensor.hal_tempratuur
    id: hallway_temprature_sensor