
  # - entity: sensor.ble_xiaomi_corridor_temperature
  # - entity: sensor.ble_xiaomi_bain_temperature
  # - entity: sensor.ble_xiaomi_chambre_temperature
  # - entity: sensor.ble_xiaomi_bureau_temperature
  # - entity: sensor.ble_xiaomi_salon_temperature
  # - entity: sensor.ble_xiaomi_reduit_temperature
  # - entity: sensor.indoor_temperature
  # - entity: sensor.ble_xiaomi_terrasse_temperature
  # - entity: sensor.outdoor_temperature
  # - entity: sensor.meteoswiss_temperature

sensor:
  - platform: homeassistant
    name: "Office temperature sensor from hassio"
    entity_id: sensor.ble_xiaomi_bureau_temperature
    id: office_temperature_sensor

  - platform: homeassistant
    name: "Living room temperature sensor from hassio"
    entity_id: sensor.ble_xiaomi_salon_temperature
    id: living_room_temperature_sensor

  - platform: homeassistant
    name: "Bedroom temperature sensor from hassio"
    entity_id: sensor.ble_xiaomi_chambre_temperature
    id: bedroom_temperature_sensor

  - platform: homeassistant
    name: "Bathroom temperature sensor from hassio"
    entity_id: sensor.ble_xiaomi_bain_temperature
    id: bathroom_temperature_sensor
    
  - platform: homeassistant
    name: "Corridor temperature sensor from hassio"
    entity_id: sensor.ble_xiaomi_corridor_temperature
    id: corridor_temperature_sensor

  - platform: homeassistant
    name: "Storage temperature sensor from hassio"
    entity_id: sensor.ble_xiaomi_reduit_temperature
    id: reduit_temperature_sensor
    
  # - platform: homeassistant
    # name: "Indoor temperature sensor from hassio"
    # entity_id: sensor.indoor_temperature
    # id: indoor_temperature_sensor


# sensor:
  # - platform: homeassistant
    # name: "Office temperature sensor from hassio"
    # entity_id: sensor.bureau_temperature
    # id: office_temperature_sensor

  # - platform: homeassistant
    # name: "Living room temperature sensor from hassio"
    # entity_id: sensor.salon_temperature
    # id: living_room_temperature_sensor

  # - platform: homeassistant
    # name: "Bedroom temperature sensor from hassio"
    # entity_id: sensor.chambre_temperature
    # id: bedroom_temperature_sensor

  # - platform: homeassistant
    # name: "Bathroom temperature sensor from hassio"
    # entity_id: sensor.bain_temperature
    # id: bathroom_temperature_sensor
    
  # - platform: homeassistant
    # name: "Corridor temperature sensor from hassio"
    # entity_id: sensor.corridor_temperature
    # id: corridor_temperature_sensor

  # - platform: homeassistant
    # name: "Storage temperature sensor from hassio"
    # entity_id: sensor.reduit_temperature
    # id: reduit_temperature_sensor
    
  # - platform: homeassistant
    # name: "Indoor temperature sensor from hassio"
    # entity_id: sensor.indoor_temperature
    # id: indoor_temperature_sensor


###### Other temperature sensor sample #######

  # - platform: dht
    # model : DHT22
    # pin: GPIO25
    # temperature:
      # name: "Switch Temperature"
      # id: switch_fan_controller_temperature
    # humidity:
      # name: "Switch Humidity"
      # id: switch_fan_controller_humidity
    # update_interval: 30s


    
  # - platform: xiaomi_lywsdcgq
    # mac_address: 58:2D:34:37:F1:10
    # temperature:
      # name: "Corridor Temperature"
      # id: xiaomi_corridor_temperature
    # humidity:
      # name: "Corridor Humidity"
      # id: xiaomi_corridor_humidity
    # battery_level:
      # name: "Corridor Xiaomi LYWSDCGQ Battery Level"
      # id: xiaomi_corridor_battery_level

      
# Connect 1-Wire bus with DS18B20 temperature sensors

# dallas:
  # - pin: GPI22
    # update_interval: 15s

# sensor:
  # - platform: dallas
    # address: 0x8b031760522cff28
    # name: "301_Heizkreis-WC-Vorlauf"
    # id: WC_Vorlauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0

  # - platform: dallas
    # address: 0x353c38f649a51b28
    # name: "301_Heizkreis-WC-Ruecklauf"
    # id: WC_Ruecklauf
    # resolution: 12
    # accuracy_decimals: 2
    # filters:
      # - offset: 0.0